export { updatePyrokinetic, PYROKINETIC_HOOKS } from './pyrokinetic-effect.ts';
export { tickHotTempered, HOT_TEMPERED_HOOKS } from './hot-tempered.ts';
export { tickManBomb, MAN_BOMB_HOOKS } from './man-bomb.ts';
export { updateRegeneration, REGENERATION_HOOKS } from './regeneration-effect.ts';
export { tickFireCough, FIRE_COUGH_HOOKS } from './fire-cough.ts';
export { applyFinalRevengeOnPlayerDeath, FINAL_REVENGE_HOOKS } from './final-revenge.ts';
export { updateJinxedTimer, updateJinxed, JINXED_HOOKS } from './jinxed-effect.ts';
export { applyRandomWeapon, RANDOM_WEAPON_HOOKS } from './random-weapon.ts';
export { applyReflexBoostedDt, REFLEX_BOOSTED_HOOKS } from './reflex-boosted.ts';
export { applyThickSkinned, THICK_SKINNED_HOOKS } from './thick-skinned.ts';
export { tickLivingFortress, LIVING_FORTRESS_HOOKS } from './living-fortress.ts';
export { HOOKS as AMMO_MANIAC_HOOKS } from './ammo-maniac.ts';
export { HOOKS as BANDAGE_HOOKS } from './bandage.ts';
export { HOOKS as BREATHING_ROOM_HOOKS } from './breathing-room.ts';
export { HOOKS as DEATH_CLOCK_HOOKS } from './death-clock.ts';
export { HOOKS as EVIL_EYES_HOOKS } from './evil-eyes-effect.ts';
export { HOOKS as FATAL_LOTTERY_HOOKS } from './fatal-lottery.ts';
export { HOOKS as GRIM_DEAL_HOOKS } from './grim-deal.ts';
export { HOOKS as INFERNAL_CONTRACT_HOOKS } from './infernal-contract.ts';
export { HOOKS as INSTANT_WINNER_HOOKS } from './instant-winner.ts';
export { HOOKS as LEAN_MEAN_EXP_MACHINE_HOOKS } from './lean-mean-exp-machine-effect.ts';
export { HOOKS as LIFELINE_50_50_HOOKS } from './lifeline-50-50.ts';
export { HOOKS as MY_FAVOURITE_WEAPON_HOOKS } from './my-favourite-weapon.ts';
export { HOOKS as PLAGUEBEARER_HOOKS } from './plaguebearer.ts';
