// Port of crimson/creatures/spawn_templates.py

import { CreatureFlags, CreatureTypeId, SpawnId, type Tint } from './spawn-ids.ts';


export interface SpawnTemplate {
    readonly spawnId: SpawnId;
    readonly typeId: CreatureTypeId | null;
    readonly flags: CreatureFlags | null;
    readonly creature: string | null;
    readonly animNote: string | null;
    readonly tint?: Tint | null;
    readonly size?: number | null;
    readonly moveSpeed?: number | null;
}

export const TYPE_ID_TO_NAME: Map<number, string> = new Map(
    Object.values(CreatureTypeId)
        .filter((v): v is number => typeof v === 'number')
        .map((v) => [v, CreatureTypeId[v].toLowerCase()]),
);

// For many template ids, tint/size/move_speed are randomized or derived from other fields.
// We only fill them in when the game uses fixed constants (and keep the rest as `null`).
export const SPAWN_TEMPLATES: readonly SpawnTemplate[] = [
    {
        spawnId: SpawnId.ZOMBIE_BOSS_SPAWNER_00,
        typeId: CreatureTypeId.ZOMBIE,
        flags: CreatureFlags.ANIM_PING_PONG | CreatureFlags.ANIM_LONG_STRIP,
        creature: 'zombie',
        animNote: 'long strip (0x40 overrides 0x4)',
        tint: [0.6, 0.6, 1.0, 0.8],
        size: 64.0,
        moveSpeed: 1.3,
    },
    {
        spawnId: SpawnId.SPIDER_SP2_SPLITTER_01,
        typeId: CreatureTypeId.SPIDER_SP2,
        flags: CreatureFlags.SPLIT_ON_DEATH,
        creature: 'spider_sp2',
        animNote: null,
        tint: [0.8, 0.7, 0.4, 1.0],
        size: 80.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_RANDOM_03,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
    },
    {
        spawnId: SpawnId.LIZARD_RANDOM_04,
        typeId: CreatureTypeId.LIZARD,
        flags: null,
        creature: 'lizard',
        animNote: null,
    },
    {
        spawnId: SpawnId.SPIDER_SP2_RANDOM_05,
        typeId: CreatureTypeId.SPIDER_SP2,
        flags: null,
        creature: 'spider_sp2',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_RANDOM_06,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_CHILD_1D_FAST_07,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [1.0, 1.0, 1.0, 1.0],
        size: 50.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_CHILD_1D_SLOW_08,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [1.0, 1.0, 1.0, 1.0],
        size: 50.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_CHILD_1D_LIMITED_09,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [1.0, 1.0, 1.0, 1.0],
        size: 40.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_CHILD_32_SLOW_0A,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [0.8, 0.7, 0.4, 1.0],
        size: 55.0,
        moveSpeed: 1.5,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_CHILD_3C_SLOW_0B,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [0.9, 0.1, 0.1, 1.0],
        size: 65.0,
        moveSpeed: 1.5,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_CHILD_31_FAST_0C,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [0.9, 0.8, 0.4, 1.0],
        size: 32.0,
        moveSpeed: 2.8,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_CHILD_31_SLOW_0D,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [0.9, 0.8, 0.4, 1.0],
        size: 32.0,
        moveSpeed: 1.3,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_RING_24_0E,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [0.9, 0.8, 0.4, 1.0],
        size: 32.0,
        moveSpeed: 2.8,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_BROWN_TRANSPARENT_0F,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.665, 0.385, 0.259, 0.56],
        size: 50.0,
        moveSpeed: 2.9,
    },
    {
        spawnId: SpawnId.ALIEN_SPAWNER_CHILD_32_FAST_10,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.ANIM_PING_PONG,
        creature: 'alien',
        animNote: 'short strip (ping-pong)',
        tint: [0.9, 0.8, 0.4, 1.0],
        size: 32.0,
        moveSpeed: 2.8,
    },
    {
        spawnId: SpawnId.FORMATION_CHAIN_LIZARD_4_11,
        typeId: CreatureTypeId.LIZARD,
        flags: null,
        creature: 'lizard',
        animNote: null,
    },
    {
        spawnId: SpawnId.FORMATION_RING_ALIEN_8_12,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.FORMATION_CHAIN_ALIEN_10_13,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.FORMATION_GRID_ALIEN_GREEN_14,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.FORMATION_GRID_ALIEN_WHITE_15,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.FORMATION_GRID_LIZARD_WHITE_16,
        typeId: CreatureTypeId.LIZARD,
        flags: null,
        creature: 'lizard',
        animNote: null,
    },
    {
        spawnId: SpawnId.FORMATION_GRID_SPIDER_SP1_WHITE_17,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
    },
    {
        spawnId: SpawnId.FORMATION_GRID_ALIEN_BRONZE_18,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.FORMATION_RING_ALIEN_5_19,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.AI1_ALIEN_BLUE_TINT_1A,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.AI1_SPIDER_SP1_BLUE_TINT_1B,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
    },
    {
        spawnId: SpawnId.AI1_LIZARD_BLUE_TINT_1C,
        typeId: CreatureTypeId.LIZARD,
        flags: null,
        creature: 'lizard',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_RANDOM_1D,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_RANDOM_1E,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_RANDOM_1F,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_RANDOM_GREEN_20,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_PURPLE_GHOST_21,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_GREEN_GHOST_22,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_GREEN_GHOST_SMALL_23,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_GREEN_24,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.1, 0.7, 0.11, 1.0],
        size: 50.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_GREEN_SMALL_25,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.1, 0.8, 0.11, 1.0],
        size: 30.0,
        moveSpeed: 2.5,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_PALE_GREEN_26,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.6, 0.8, 0.6, 1.0],
        size: 45.0,
        moveSpeed: 2.2,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_WEAPON_BONUS_27,
        typeId: CreatureTypeId.ALIEN,
        flags: CreatureFlags.BONUS_ON_DEATH,
        creature: 'alien',
        animNote: 'bonus_id=WEAPON (3), duration_override=5 (packed in link_index)',
        tint: [1.0, 0.8, 0.1, 1.0],
        size: 45.0,
        moveSpeed: 2.1,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_PURPLE_28,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.7, 0.1, 0.51, 1.0],
        size: 55.0,
        moveSpeed: 1.7,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_GREY_BRUTE_29,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.8, 0.8, 0.8, 1.0],
        size: 70.0,
        moveSpeed: 2.5,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_GREY_FAST_2A,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.3, 0.3, 0.3, 1.0],
        size: 60.0,
        moveSpeed: 3.1,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_RED_FAST_2B,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [1.0, 0.3, 0.3, 1.0],
        size: 35.0,
        moveSpeed: 3.6,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_RED_BOSS_2C,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.85, 0.2, 0.2, 1.0],
        size: 80.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.ALIEN_CONST_CYAN_AI2_2D,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.0, 0.9, 0.8, 1.0],
        size: 38.0,
        moveSpeed: 3.1,
    },
    {
        spawnId: SpawnId.LIZARD_RANDOM_2E,
        typeId: CreatureTypeId.LIZARD,
        flags: null,
        creature: 'lizard',
        animNote: null,
    },
    {
        spawnId: SpawnId.LIZARD_CONST_GREY_2F,
        typeId: CreatureTypeId.LIZARD,
        flags: null,
        creature: 'lizard',
        animNote: null,
    },
    {
        spawnId: SpawnId.LIZARD_CONST_YELLOW_BOSS_30,
        typeId: CreatureTypeId.LIZARD,
        flags: null,
        creature: 'lizard',
        animNote: null,
    },
    {
        spawnId: SpawnId.LIZARD_RANDOM_31,
        typeId: CreatureTypeId.LIZARD,
        flags: null,
        creature: 'lizard',
        animNote: null,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_RANDOM_32,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_RANDOM_RED_33,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_RANDOM_GREEN_34,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
    },
    {
        spawnId: SpawnId.SPIDER_SP2_RANDOM_35,
        typeId: CreatureTypeId.SPIDER_SP2,
        flags: null,
        creature: 'spider_sp2',
        animNote: null,
    },
    {
        spawnId: SpawnId.ALIEN_AI7_ORBITER_36,
        typeId: CreatureTypeId.ALIEN,
        flags: null,
        creature: 'alien',
        animNote: null,
        tint: [0.65, null, 0.95, 1.0],
        size: 50.0,
        moveSpeed: 1.8,
    },
    {
        spawnId: SpawnId.SPIDER_SP2_RANGED_VARIANT_37,
        typeId: CreatureTypeId.SPIDER_SP2,
        flags: CreatureFlags.RANGED_ATTACK_VARIANT,
        creature: 'spider_sp2',
        animNote: null,
        tint: [1.0, 0.75, 0.1, 1.0],
        moveSpeed: 3.2,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_AI7_TIMER_38,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: CreatureFlags.AI7_LINK_TIMER,
        creature: 'spider_sp1',
        animNote: null,
        tint: [1.0, 0.75, 0.1, 1.0],
        moveSpeed: 4.8,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_AI7_TIMER_WEAK_39,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: CreatureFlags.AI7_LINK_TIMER,
        creature: 'spider_sp1',
        animNote: null,
        tint: [0.8, 0.65, 0.1, 1.0],
        moveSpeed: 4.8,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_CONST_SHOCK_BOSS_3A,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: CreatureFlags.RANGED_ATTACK_SHOCK,
        creature: 'spider_sp1',
        animNote: 'projectile_type=9',
        tint: [1.0, 1.0, 1.0, 1.0],
        size: 64.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_CONST_RED_BOSS_3B,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
        tint: [0.9, 0.0, 0.0, 1.0],
        size: 70.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_CONST_RANGED_VARIANT_3C,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: CreatureFlags.RANGED_ATTACK_VARIANT,
        creature: 'spider_sp1',
        animNote: 'projectile_type=26 (packed in orbit_radius)',
        tint: [0.9, 0.1, 0.1, 1.0],
        size: 40.0,
        moveSpeed: 2.0,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_RANDOM_3D,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
        tint: [null, null, null, 1.0],
        moveSpeed: 2.6,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_CONST_WHITE_FAST_3E,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
        tint: [1.0, 1.0, 1.0, 1.0],
        size: 64.0,
        moveSpeed: 2.8,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_CONST_BROWN_SMALL_3F,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
        tint: [0.7, 0.4, 0.1, 1.0],
        size: 35.0,
        moveSpeed: 2.3,
    },
    {
        spawnId: SpawnId.SPIDER_SP1_CONST_BLUE_40,
        typeId: CreatureTypeId.SPIDER_SP1,
        flags: null,
        creature: 'spider_sp1',
        animNote: null,
        tint: [0.5, 0.6, 0.9, 1.0],
        size: 45.0,
        moveSpeed: 2.2,
    },
    {
        spawnId: SpawnId.ZOMBIE_RANDOM_41,
        typeId: CreatureTypeId.ZOMBIE,
        flags: null,
        creature: 'zombie',
        animNote: null,
        tint: [null, null, null, 1.0],
    },
    {
        spawnId: SpawnId.ZOMBIE_CONST_GREY_42,
        typeId: CreatureTypeId.ZOMBIE,
        flags: null,
        creature: 'zombie',
        animNote: null,
        tint: [0.9, 0.9, 0.9, 1.0],
        size: 45.0,
        moveSpeed: 1.7,
    },
    {
        spawnId: SpawnId.ZOMBIE_CONST_GREEN_BRUTE_43,
        typeId: CreatureTypeId.ZOMBIE,
        flags: null,
        creature: 'zombie',
        animNote: null,
        tint: [0.2, 0.6, 0.1, 1.0],
        size: 70.0,
        moveSpeed: 2.1,
    },
];

export const SPAWN_ID_TO_TEMPLATE: Map<SpawnId, SpawnTemplate> = new Map(
    SPAWN_TEMPLATES.map((entry) => [entry.spawnId, entry]),
);
