// Port of crimson/creatures/spawn_templates.py

import { CreatureFlags, CreatureTypeId, SpawnId, type Tint } from './spawn-ids';


export interface SpawnTemplate {
    readonly spawnId: SpawnId;
    readonly typeId: CreatureTypeId | null;
    readonly flags: CreatureFlags | null;
    readonly creature: string | null;
    readonly animNote: string | null;
    readonly tint: Tint | null;
    readonly size: number | null;
    readonly moveSpeed: number | null;
}

function tmpl(
    spawnId: SpawnId,
    typeId: CreatureTypeId | null,
    flags: CreatureFlags | null,
    creature: string | null,
    animNote: string | null,
    tint: Tint | null = null,
    size: number | null = null,
    moveSpeed: number | null = null,
): SpawnTemplate {
    return { spawnId, typeId, flags, creature, animNote, tint, size, moveSpeed };
}

export const TYPE_ID_TO_NAME: Map<number, string> = new Map(
    Object.values(CreatureTypeId)
        .filter((v): v is number => typeof v === 'number')
        .map((v) => [v, CreatureTypeId[v].toLowerCase()]),
);

// For many template ids, tint/size/move_speed are randomized or derived from other fields.
// We only fill them in when the game uses fixed constants (and keep the rest as `null`).
export const SPAWN_TEMPLATES: readonly SpawnTemplate[] = [
    tmpl(
        SpawnId.ZOMBIE_BOSS_SPAWNER_00,
        CreatureTypeId.ZOMBIE,
        CreatureFlags.ANIM_PING_PONG | CreatureFlags.ANIM_LONG_STRIP,
        'zombie',
        'long strip (0x40 overrides 0x4)',
        [0.6, 0.6, 1.0, 0.8],
        64.0,
        1.3,
    ),
    tmpl(
        SpawnId.SPIDER_SP2_SPLITTER_01,
        CreatureTypeId.SPIDER_SP2,
        CreatureFlags.SPLIT_ON_DEATH,
        'spider_sp2',
        null,
        [0.8, 0.7, 0.4, 1.0],
        80.0,
        2.0,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_RANDOM_03,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
    ),
    tmpl(
        SpawnId.LIZARD_RANDOM_04,
        CreatureTypeId.LIZARD,
        null,
        'lizard',
        null,
    ),
    tmpl(
        SpawnId.SPIDER_SP2_RANDOM_05,
        CreatureTypeId.SPIDER_SP2,
        null,
        'spider_sp2',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_RANDOM_06,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_CHILD_1D_FAST_07,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [1.0, 1.0, 1.0, 1.0],
        50.0,
        2.0,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_CHILD_1D_SLOW_08,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [1.0, 1.0, 1.0, 1.0],
        50.0,
        2.0,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_CHILD_1D_LIMITED_09,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [1.0, 1.0, 1.0, 1.0],
        40.0,
        2.0,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_CHILD_32_SLOW_0A,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [0.8, 0.7, 0.4, 1.0],
        55.0,
        1.5,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_CHILD_3C_SLOW_0B,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [0.9, 0.1, 0.1, 1.0],
        65.0,
        1.5,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_CHILD_31_FAST_0C,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [0.9, 0.8, 0.4, 1.0],
        32.0,
        2.8,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_CHILD_31_SLOW_0D,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [0.9, 0.8, 0.4, 1.0],
        32.0,
        1.3,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_RING_24_0E,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [0.9, 0.8, 0.4, 1.0],
        32.0,
        2.8,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_BROWN_TRANSPARENT_0F,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.665, 0.385, 0.259, 0.56],
        50.0,
        2.9,
    ),
    tmpl(
        SpawnId.ALIEN_SPAWNER_CHILD_32_FAST_10,
        CreatureTypeId.ALIEN,
        CreatureFlags.ANIM_PING_PONG,
        'alien',
        'short strip (ping-pong)',
        [0.9, 0.8, 0.4, 1.0],
        32.0,
        2.8,
    ),
    tmpl(
        SpawnId.FORMATION_CHAIN_LIZARD_4_11,
        CreatureTypeId.LIZARD,
        null,
        'lizard',
        null,
    ),
    tmpl(
        SpawnId.FORMATION_RING_ALIEN_8_12,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.FORMATION_CHAIN_ALIEN_10_13,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.FORMATION_GRID_ALIEN_GREEN_14,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.FORMATION_GRID_ALIEN_WHITE_15,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.FORMATION_GRID_LIZARD_WHITE_16,
        CreatureTypeId.LIZARD,
        null,
        'lizard',
        null,
    ),
    tmpl(
        SpawnId.FORMATION_GRID_SPIDER_SP1_WHITE_17,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
    ),
    tmpl(
        SpawnId.FORMATION_GRID_ALIEN_BRONZE_18,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.FORMATION_RING_ALIEN_5_19,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.AI1_ALIEN_BLUE_TINT_1A,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.AI1_SPIDER_SP1_BLUE_TINT_1B,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
    ),
    tmpl(
        SpawnId.AI1_LIZARD_BLUE_TINT_1C,
        CreatureTypeId.LIZARD,
        null,
        'lizard',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_RANDOM_1D,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_RANDOM_1E,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_RANDOM_1F,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_RANDOM_GREEN_20,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_PURPLE_GHOST_21,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_GREEN_GHOST_22,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_GREEN_GHOST_SMALL_23,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_GREEN_24,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.1, 0.7, 0.11, 1.0],
        50.0,
        2.0,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_GREEN_SMALL_25,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.1, 0.8, 0.11, 1.0],
        30.0,
        2.5,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_PALE_GREEN_26,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.6, 0.8, 0.6, 1.0],
        45.0,
        2.2,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_WEAPON_BONUS_27,
        CreatureTypeId.ALIEN,
        CreatureFlags.BONUS_ON_DEATH,
        'alien',
        'bonus_id=WEAPON (3), duration_override=5 (packed in link_index)',
        [1.0, 0.8, 0.1, 1.0],
        45.0,
        2.1,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_PURPLE_28,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.7, 0.1, 0.51, 1.0],
        55.0,
        1.7,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_GREY_BRUTE_29,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.8, 0.8, 0.8, 1.0],
        70.0,
        2.5,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_GREY_FAST_2A,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.3, 0.3, 0.3, 1.0],
        60.0,
        3.1,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_RED_FAST_2B,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [1.0, 0.3, 0.3, 1.0],
        35.0,
        3.6,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_RED_BOSS_2C,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.85, 0.2, 0.2, 1.0],
        80.0,
        2.0,
    ),
    tmpl(
        SpawnId.ALIEN_CONST_CYAN_AI2_2D,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.0, 0.9, 0.8, 1.0],
        38.0,
        3.1,
    ),
    tmpl(
        SpawnId.LIZARD_RANDOM_2E,
        CreatureTypeId.LIZARD,
        null,
        'lizard',
        null,
    ),
    tmpl(
        SpawnId.LIZARD_CONST_GREY_2F,
        CreatureTypeId.LIZARD,
        null,
        'lizard',
        null,
    ),
    tmpl(
        SpawnId.LIZARD_CONST_YELLOW_BOSS_30,
        CreatureTypeId.LIZARD,
        null,
        'lizard',
        null,
    ),
    tmpl(
        SpawnId.LIZARD_RANDOM_31,
        CreatureTypeId.LIZARD,
        null,
        'lizard',
        null,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_RANDOM_32,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_RANDOM_RED_33,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_RANDOM_GREEN_34,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
    ),
    tmpl(
        SpawnId.SPIDER_SP2_RANDOM_35,
        CreatureTypeId.SPIDER_SP2,
        null,
        'spider_sp2',
        null,
    ),
    tmpl(
        SpawnId.ALIEN_AI7_ORBITER_36,
        CreatureTypeId.ALIEN,
        null,
        'alien',
        null,
        [0.65, null, 0.95, 1.0],
        50.0,
        1.8,
    ),
    tmpl(
        SpawnId.SPIDER_SP2_RANGED_VARIANT_37,
        CreatureTypeId.SPIDER_SP2,
        CreatureFlags.RANGED_ATTACK_VARIANT,
        'spider_sp2',
        null,
        [1.0, 0.75, 0.1, 1.0],
        null,
        3.2,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_AI7_TIMER_38,
        CreatureTypeId.SPIDER_SP1,
        CreatureFlags.AI7_LINK_TIMER,
        'spider_sp1',
        null,
        [1.0, 0.75, 0.1, 1.0],
        null,
        4.8,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_AI7_TIMER_WEAK_39,
        CreatureTypeId.SPIDER_SP1,
        CreatureFlags.AI7_LINK_TIMER,
        'spider_sp1',
        null,
        [0.8, 0.65, 0.1, 1.0],
        null,
        4.8,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_CONST_SHOCK_BOSS_3A,
        CreatureTypeId.SPIDER_SP1,
        CreatureFlags.RANGED_ATTACK_SHOCK,
        'spider_sp1',
        'projectile_type=9',
        [1.0, 1.0, 1.0, 1.0],
        64.0,
        2.0,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_CONST_RED_BOSS_3B,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
        [0.9, 0.0, 0.0, 1.0],
        70.0,
        2.0,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_CONST_RANGED_VARIANT_3C,
        CreatureTypeId.SPIDER_SP1,
        CreatureFlags.RANGED_ATTACK_VARIANT,
        'spider_sp1',
        'projectile_type=26 (packed in orbit_radius)',
        [0.9, 0.1, 0.1, 1.0],
        40.0,
        2.0,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_RANDOM_3D,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
        [null, null, null, 1.0],
        null,
        2.6,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_CONST_WHITE_FAST_3E,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
        [1.0, 1.0, 1.0, 1.0],
        64.0,
        2.8,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_CONST_BROWN_SMALL_3F,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
        [0.7, 0.4, 0.1, 1.0],
        35.0,
        2.3,
    ),
    tmpl(
        SpawnId.SPIDER_SP1_CONST_BLUE_40,
        CreatureTypeId.SPIDER_SP1,
        null,
        'spider_sp1',
        null,
        [0.5, 0.6, 0.9, 1.0],
        45.0,
        2.2,
    ),
    tmpl(
        SpawnId.ZOMBIE_RANDOM_41,
        CreatureTypeId.ZOMBIE,
        null,
        'zombie',
        null,
        [null, null, null, 1.0],
    ),
    tmpl(
        SpawnId.ZOMBIE_CONST_GREY_42,
        CreatureTypeId.ZOMBIE,
        null,
        'zombie',
        null,
        [0.9, 0.9, 0.9, 1.0],
        45.0,
        1.7,
    ),
    tmpl(
        SpawnId.ZOMBIE_CONST_GREEN_BRUTE_43,
        CreatureTypeId.ZOMBIE,
        null,
        'zombie',
        null,
        [0.2, 0.6, 0.1, 1.0],
        70.0,
        2.1,
    ),
];

export const SPAWN_ID_TO_TEMPLATE: Map<SpawnId, SpawnTemplate> = new Map(
    SPAWN_TEMPLATES.map((entry) => [entry.spawnId, entry]),
);
